name: Test

on:
    push:
        branches: main
    pull_request: ~

jobs:
    test-php-81:
        name: Test PHP 8.1
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP 8.1
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    tools: composer:v2

            -   name: Install composer dependencies
                run: composer install --prefer-dist --no-progress --no-suggest

            -   name: Run GrumPHP
                run: vendor/bin/grumphp run
    test-php-82:
        name: Test PHP 8.2
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP 8.2
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2
                    tools: composer:v2

            -   name: Install composer dependencies
                run: composer install --prefer-dist --no-progress --no-suggest

            -   name: Run GrumPHP
                run: PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/grumphp run
